### ISSUE TITLE
framerate after update is broken

### ISSUE THREAD

**Issue by shadowstardx** [ItsEasyActually/AutoDemo_WindyValley#7]
the level doesn't run at a stable frame rate anymore after latest update

**Comment by ItsEasyActually** [comment]
the last update was 5+ years ago. so whatever you're referring to as getting an update wasn't this mod unless you somehow had been using an older release. 

if you happen to be referring to the mod manager and/or mod loader, I can tell you the mod runs fine on it sans the two known problems mentioned below.

there are two other reasons for performance problems though, when running it with the SADX Limit Break mod or running on older hardware due to some not well optimized or memory efficient coding at the time.

**Comment by shadowstardx** [comment]
I still dont know why this stage completely broke after the mod loader update. gonna try clean install first.
